### ISSUE TITLE
Rephrase questions depending on parent/ child answering

### ISSUE THREAD

**Issue by gauravkeerthi** [bettersg/kidsplaysafer#45]
<img width="180" alt="Screenshot 2022-06-05 at 5 48 45 PM" src="https://user-images.githubusercontent.com/6855844/172042054-f0188d3e-41e8-4714-9077-642d362ac80a.png">

when the child is answering, the phrasing of the question makes sense. 

<img width="180" alt="Screenshot 2022-06-05 at 5 48 45 PM" src="https://user-images.githubusercontent.com/6855844/172042059-13401ab5-163c-49f1-8c79-f31f26ff0207.png">

When the parent is answering what they expect the child to answer, the phrasing does not make sense. 

Perhaps the question can include a simple %respondee% that is replaced by “you” (if the child is answering) or “your child“   - or, if there is no elegant solution, can just have two questions (the child-parent pair) each time.

**Comment by gauravkeerthi** [comment]
Or perhaps just the simplest solution is to add a preface to the parent’s screen: “how did you expect your child to answer this?”

**Comment by maclauss** [comment]
Hi @gauravkeerthi, that's a good point yes. The original design considered it yes, should be an easy fix, we can even consider using the selected avatar to use the correct gender (his / her). Although those days I'm not sure it's accepted to do that anymore... 😅

<img width="180" alt="Screenshot 2022-06-05 at 5 48 45 PM" src="https://user-images.githubusercontent.com/2435295/172044817-d1556da2-cafa-4d93-aa4a-1c45e7010e17.png">
<img width="180" alt="Screenshot 2022-06-05 at 5 48 31 PM" src="https://user-images.githubusercontent.com/2435295/172044824-49e5cddc-e34c-49fb-a9a6-2118b786259a.png">
